- lib/ash_authentication/oauth2_authentication/plug.ex
- lib/ash_authentication/plug.ex
- lib/ash_authentication/plug/helpers.ex
(ie it's an error from assent).
> fix(OAuth2Authentication): Return the failure reason even if it's not a changeset.

- lib/ash_authentication.ex
- lib/ash_authentication/add_ons/confirmation/actions.ex
- lib/ash_authentication/add_ons/confirmation/strategy.ex
- lib/ash_authentication/strategies/oauth2/actions.ex
- lib/ash_authentication/strategies/oauth2/strategy.ex
- lib/ash_authentication/strategies/password/actions.ex
- lib/ash_authentication/strategies/password/strategy.ex
- lib/ash_authentication/strategy.ex
- test/ash_authentication/add_ons/confirmation/actions_test.exs
- test/ash_authentication/add_ons/confirmation/strategy_test.exs
- test/ash_authentication/strategies/oauth2/actions_test.exs
- test/ash_authentication/strategies/oauth2/strategy_test.exs
- test/ash_authentication/strategies/password/actions_test.exs
- test/ash_authentication/strategies/password/strategy_test.exs
> improvement(actions): All actions now take optional arguments for the underlying API call.

- lib/ash_authentication.ex
- lib/ash_authentication/application.ex
- lib/ash_authentication/plug/helpers.ex
- lib/ash_authentication/supervisor.ex
- lib/ash_authentication/token_resource.ex
- lib/ash_authentication/token_resource/expunger.ex
> improvement(supervisor): require that the user adds the supervisor to their OTP app.

- documentation/getting_started/getting_started_02_phoenix.md
Closes https://github.com/team-alembic/ash_authentication_phoenix/issues/31
> chore(docs): Add tailwind configuration to phoenix guide.

- lib/ash_authentication/utils.ex
Not sure if this will resolve the issues, but is worth a try.
> improvement: try a simpler way of ensuring module is compiled

- config/config.exs
- documentation/topics/policies-on-authentication-resources.md
- lib/ash_authentication.ex
- lib/ash_authentication/add_ons/confirmation/actions.ex
- lib/ash_authentication/add_ons/confirmation/transformer.ex
- lib/ash_authentication/checks/ash_authentication_interaction.ex
- lib/ash_authentication/strategies/oauth2/actions.ex
- lib/ash_authentication/strategies/password/actions.ex
- lib/ash_authentication/token_resource/actions.ex
- lib/ash_authentication/token_resource/verifier.ex
- lib/ash_authentication/user_identity/actions.ex
- lib/ash_authentication/verifier.ex
- mix.exs
fix: improve some error message/validation logic
> improvement: add policy utilities and accompanying guide

- lib/ash_authentication/jwt.ex
- lib/ash_authentication/plug/helpers.ex
This allows tracking additional user information in the token, if necessary.
> improvement: add user context when creating tokens

- documentation/tutorials/integrating-ash-authentication-and-phoenix.md
> docs: Add a small warning about defining the failure template.

- lib/ash_authentication/strategies/password/sign_in_preparation.ex
fix: use configured hashed_password_field
> fix: don't call `hash_provider.valid?` on `nil` values

- documentation/tutorials/getting-started-with-authentication.md
- documentation/tutorials/integrating-ash-authentication-and-phoenix.md
Compiler complains about hashed_password needing to be sensitive
> Tweaks to doco

- documentation/tutorials/github-quickstart.md
- lib/ash_authentication/dsl.ex
This is basically a copy-pasta of #142
> docs: Add GitHub quick start guide.

- lib/ash_authentication/strategies/password/hash_password_change.ex
- lib/ash_authentication/strategies/password/password_validation.ex
- test/ash_authentication/strategies/password/hash_password_change_test.exs
- test/ash_authentication/strategies/password/password_validation_test.exs
> feat(PasswordValidation): Add a validation which can check a password.

- lib/ash_authentication/strategies/password/transformer.ex
> fix(Password): validate fields using both methods of allowing nil input.

- .github/workflows/elixir_lib.yml
- lib/ash_authentication.ex
- lib/ash_authentication/token_resource.ex
- lib/ash_authentication/user_identity.ex
docs: hide bullet-style docs from ash_hq
> chore: add clear condition on release

- lib/ash_authentication/plug/helpers.ex
- test/ash_authentication/plug/helpers_test.exs
- test/support/example/user_with_token_required.ex
> fix: don't allow special purpose tokens to be used for sign in.

- lib/ash_authentication.ex
- lib/ash_authentication/dsl.ex
- lib/ash_authentication/strategies/magic_link/request_preparation.ex
- lib/ash_authentication/strategies/password/request_password_reset_preparation.ex
- lib/ash_authentication/strategies/password/sign_in_preparation.ex
- lib/ash_authentication/strategies/password/transformer.ex
- lib/ash_authentication/transformer/set_select_for_senders.ex
- test/ash_authentication/strategies/password/actions_test.exs
- test/support/example/user.ex
fix: select `hashed_password` on sign in preparation
> improvement: add select_for_senders

- documentation/tutorials/getting-started-with-authentication.md
Add note for those using policies
> docs: Update getting-started-with-authentication.md

- lib/ash_authentication/strategies/oauth2.ex
I found a few typos while reviewing the docs.  I decided to submit a PR to fix!  Thanks for creating this framework.
> Correct oauth2 and getting started typos

- documentation/tutorials/getting-started-with-authentication.md
This is a tiny clarification, but it would have helped me a bit if I had it.
> Clarify which file contains the snippet

- lib/ash_authentication/token_resource/actions.ex
> fix(TokenResource): don't silently drop notifications about token removal.

- documentation/tutorials/auth0-quickstart.md
When I first followed [The Auth0 Quickstartl](https://hexdocs.pm/ash_authentication/auth0-quickstart.html), I did not know from which starting position I could follow this quick start.
I believe this PR will clarify it for others.
> Clarify starting position 🏎️

- lib/ash_authentication/add_ons/confirmation/actions.ex
- test/ash_authentication/add_ons/confirmation/actions_test.exs
Fixes a potential issue where the confirmation token can be used multiple times, potentially opening a replay attack.
Closes #618
> fix(Confirmation): Only allow the confirmation token to be used once.

- lib/ash_authentication/strategies/password/verifier.ex
> improvement: validate that tokens are enabled when password resets are enabled.

- documentation/tutorials/confirmation.md
Closes #771 
Two main changes:
1. Fix the bugs related to encoding the tokens in the URLs.
2. Bring the modules of the guide in line with the Reset Password section of AshAuthenticationPhoenix, the style of which I personally like more.
Number 2 obviously isn't a mistake, but this guide is a bit out-of-sync if you follow the Getting Started guide from AshAuthentication and continue with the AshAuthenticationPhoenix guide.
> docs: fix mistakes in the 'Confirmation' guide

- test/mix/tasks/ash_authentication.add_strategy_test.exs
Should I create PRs for single character typos?
> Fix typo in test description

- documentation/dsls/DSL:-AshAuthentication.Strategy.OAuth2.md
create action needed to match strategy name
> fix oauth2 example

- documentation/tutorials/confirmation.md
Very small issue, an inconsistent module name in the docs.
> Wrong module name

- .formatter.exs
- documentation/dsls/DSL-AshAuthentication.Strategy.Password.md
- documentation/tutorials/confirmation.md
- lib/ash_authentication/errors/unconfirmed_user.ex
- lib/ash_authentication/strategies/password.ex
- lib/ash_authentication/strategies/password/actions.ex
- lib/ash_authentication/strategies/password/dsl.ex
- lib/ash_authentication/strategies/password/sign_in_preparation.ex
- test/ash_authentication/strategies/password/plug_test.exs
- test/support/example/user.ex
This PR tries to find a nice way to make the account confirmation mandatory in order to sign in.
> Account confirmation

- lib/ash_authentication/strategies/google/dsl.ex
Patch applied to fix `Assent 0.3.0` breaking changes. Issue: https://github.com/team-alembic/ash_authentication/issues/880
> `:google` strategy fixed

- mix.exs
> Correctly pinned version

- lib/mix/tasks/ash_authentication.add_strategy.ex
> feat: swoosh email sender

- .formatter.exs
- lib/ash_authentication/strategies/oauth2.ex
- lib/ash_authentication/strategies/oauth2/dsl.ex
- lib/ash_authentication/strategies/oauth2/plug.ex
- lib/ash_authentication/strategies/oidc/dsl.ex
- lib/ash_authentication/strategies/oidc/verifier.ex
Add support for Code Verifier as described here:
https://hexdocs.pm/assent/Assent.Strategy.OAuth2.html
> Add support for OAuth2 Code Verifier

- lib/ash_authentication/strategies/magic_link.ex
- lib/ash_authentication/strategies/magic_link/request.ex
- lib/ash_authentication/strategies/magic_link/sign_in_preparation.ex
Related to the issue in: https://github.com/alemoreau/ash_multitenancy_repro
Not sure if right approach but it does fix the issue.
> fix: Multitenant magic link redirect

- documentation/topics/testing.md
Howdy!
As per our brief [forum discussion](https://elixirforum.com/t/how-to-test-live-views-with-ash-authentication-plugs/59814/17?u=sodapopcan), here is some documentation on how to create a `register_and_log_in_user` test helper.
> Document creating a helper for testing authenticated LiveViews

- documentation/topics/testing.md
Apologies for the extra PR, I noticed I made a typo.
> doc: Fix typo

- lib/ash_authentication/strategies/password/sign_in_with_token_preparation.ex
This change passes along the tenant from the sign_in token claims(if it exists) to the long-lived token claims that is returned to the AuthController.
> improvement: pass along the tenant claim(if exists) to the long-lived token

- documentation/tutorials/auth0.md
Add documentation for the logout process when using Auth0 #346
> doc: logout process for auth0
