team-alembic/ash_authentication

.github/workflows/elixir_lib.yml, config/dev.exs, config/test.exs, documentation/getting_started/getting_started_01_basic_setup.md, lib/ash_authentication/dsl.ex, lib/ash_authentication/jwt.ex, lib/ash_authentication/jwt/config.ex, lib/ash_authentication/secret.ex, lib/ash_authentication/spark_doc_index.ex, test/support/example/user.ex
Use the `AshAuthentication.Secret` behaviour, rather than asking the user to explicitly set it in their application environment.
=> Improvement(Jwt)!: use secrets for jwt config

lib/ash_authentication/add_ons/confirmation/actions.ex, lib/ash_authentication/add_ons/confirmation/confirm_change.ex, lib/ash_authentication/add_ons/confirmation/transformer.ex, lib/ash_authentication/info.ex, lib/ash_authentication/strategies/oauth2/actions.ex, lib/ash_authentication/strategies/oauth2/identity_change.ex, lib/ash_authentication/strategies/oauth2/sign_in_preparation.ex, lib/ash_authentication/strategies/oauth2/transformer.ex, lib/ash_authentication/strategies/password/actions.ex, lib/ash_authentication/strategies/password/hash_password_change.ex, lib/ash_authentication/strategies/password/password_confirmation_validation.ex, lib/ash_authentication/strategies/password/request_password_reset_preparation.ex, lib/ash_authentication/strategies/password/reset_token_validation.ex, lib/ash_authentication/strategies/password/sign_in_preparation.ex, lib/ash_authentication/strategies/password/transformer.ex, test/support/data_case.ex
The action -> strategy mapping is now stored directly in the resource DSL.
Closes #84.
=> improvement: remove the need for a strategy in changeset/query contexts.

README.md, lib/ash_authentication.ex
This PR fixes a doc error in the strategy example for an user.
Original example:
```elixir
strategies do
password do
identity_field :email
hashed_password_field :hashed_password
end
end
```
Correct example:
```elixir
strategies do
password :password do
identity_field :email
hashed_password_field :hashed_password
end
end
```
=> docs: fixed the strategy example in the `Usage` section of `README.md`.

lib/ash_authentication/plug/router.ex, lib/ash_authentication/strategies/oauth2/plug.ex, lib/ash_authentication/strategies/password/plug.ex
=> improvement: Set Ash actor and tenant when executing internal plugs.

lib/ash_authentication/add_ons/confirmation/confirmation_hook_change.ex, lib/ash_authentication/dsl.ex, lib/ash_authentication/sender_function.ex, lib/ash_authentication/strategies/password/resettable.ex, test/ash_authentication/add_ons/confirmation/confirmation_hook_change_test.exs, test/support/example/user.ex
Changes the behaviour of the `ConfirmationHookChange` to pass the original, unmodified changeset in the sender options so that senders can account for inhibited changes.
=> fix(Confirmation): send the original changeset to confirmation senders.

config/dev.exs, lib/ash_authentication/application.ex, lib/ash_authentication/debug.ex, lib/ash_authentication/errors/authentication_failed.ex, lib/ash_authentication/strategies/oauth2/actions.ex, lib/ash_authentication/strategies/oauth2/sign_in_preparation.ex, lib/ash_authentication/strategies/password/actions.ex, lib/ash_authentication/strategies/password/sign_in_preparation.ex
This allows for a better debugging experience when trying to understand why an authentication action is failing.
Closes #128.
=> improvement(AuthenticationFailed): store a `caused_by` value in authentication failures.

lib/ash_authentication/plug.ex
These docs for Phoenix should say `plug` where they currently say `pipe`.
=> Fix `pipe` typos

documentation/tutorials/getting-started-with-authentication.md
There's a missing `do` in the getting started guide.
=> Add missing `do`

lib/ash_authentication/strategies/password/transformer.ex
I'm not sure why I added that. Seems wrong.
=> fix(Password.Transformer): don't force users to define a `hashed_password` argument to the register action.

lib/ash_authentication/strategies/oauth2/sign_in_preparation.ex, test/ash_authentication/strategies/oauth2/actions_test.exs, test/support/example/user.ex
I noticed sign-in does throw an error when registration and identity resource are disabled. The test might need some work, but I couldn't override `registration_identity` in the test like this:
```elixir
strategy = %{strategy | registration_enabled?: false, identity_resource: false}
```
=> Fix sign in preparation without identity resource

lib/ash_authentication/add_ons/confirmation.ex
Small hiccup in the docs for adding confirmation - not a huge blocker, but could slow folks down on adoption.
=> docs: Updates confirmation docs with sender and identities

lib/ash_authentication/strategies/oauth2/identity_change.ex
Noticed this when I changed from the default `user_id` to e.g. `account_id`:
```ex
[error] Something went wrong in authentication
activity: {:oauth2, :callback}
reason: ** (Ash.Error.Invalid) Input Invalid
* argument account_id is required
(ash 2.5.16) lib/ash/changeset/changeset.ex:860: anonymous fn/2 in Ash.Changeset.require_arguments/2
(elixir 1.14.3) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
(ash 2.5.16) lib/ash/changeset/changeset.ex:706: Ash.Changeset.do_for_action/4
(ash_authentication 3.7.9) lib/ash_authentication/user_identity/actions.ex:29: AshAuthentication.UserIdentity.Actions.upsert/2
(ash_authentication 3.7.9) lib/ash_authentication/strategies/oauth2/identity_change.ex:33: anonymous fn/3 in AshAuthentication.Strategy.OAuth2.IdentityChange.do_change/2
...
```
=> fix: respect `identity_relationship_user_id_attribute` on `Strategy.OAuth2.IdentityChange`

mix.exs
The rational is strange for this one, but I believe there is some kind of bug in dependency resolution when doing `x and y or z`, due to very cryptic errors during dependency resolution in an app for which the details I can't really share.
spark 1.0+ is stable, so lets just bump it
=> improvement: require spark ~> 1.0

lib/ash_authentication/strategies/password/sign_in_preparation.ex, lib/ash_authentication/strategies/password/sign_in_with_token_preparation.ex
Basically a copy-pasta of the `find_strategy/3` function from `HashPasswordChange` to allow for the strategy to be passed in via the context(s) or preparation options.
=> fix(Strategy.Password): Preparations should allow strategy to be passed in.

lib/ash_authentication/strategies/password/password_validation.ex
Use Logger.warning instead of Logger.warn, [which is deprecated as of elixir 1.15](https://github.com/elixir-lang/elixir/blob/v1.15/CHANGELOG.md#logger-2).
Logger.warning [is available since elixir 1.11](https://hexdocs.pm/logger/1.15.0/Logger.html#warning/2), and since [this project requires at least elixir 1.13](https://github.com/team-alembic/ash_authentication/blob/main/mix.exs#L12), this is a safe change.
=> fix: fix Logger deprecations for elixir 1.15

lib/ash_authentication/transformer.ex
=> fix: ensure that the `current_` atom exists at compile time.

lib/ash_authentication/jwt.ex
Should be `map` instead of `%{}` for `extra_claims`. Was getting "has no local return" from dialyzer because of this. (This is the only place where `%{}` is used instead of `map` in spec.)
=> fix: correct spec for `Jwt.token_for_user`

lib/ash_authentication/plug/helpers.ex, test/ash_authentication/plug/helpers_test.exs
Make the token record available via the connection when a bearer token header is used. In my case, this allows me to implement session inactivity timeout outside in my application.
=> improvement: assign the token record to the connection assigns

lib/ash_authentication/application.ex, lib/ash_authentication/strategies/oauth2/plug.ex
assent v0.2.6
Added [Assent.HTTPAdapter.Finch](https://hexdocs.pm/assent/Assent.HTTPAdapter.Finch.html)
Deprecated [Assent.HTTPAdapter.Mint](https://hexdocs.pm/assent/Assent.HTTPAdapter.Mint.html)
=> fix deprecated mint httpadapter on assent

lib/ash_authentication/strategies/oauth2.ex
I think this is a mistake. I didn't cast about for more instances of it.
=> Fix missing piece of module path in doc example

documentation/tutorials/google-quickstart.md
Adds a simple guide on how to configure Google sign in and registration with the oauth2 strategy
=> docs: adds guide for oauth2 strategy with google

lib/ash_authentication/user_identity/upsert_identity_change.ex
Not sure if this is a fix that is wanted. But I had Google OAuth fail any time I switched the identity_resource thing on in the strategy.
=> Add id as an option for sourcing uid for UserIdentity

documentation/dsls/DSL:-AshAuthentication.Strategy.OAuth2.cheatmd, documentation/dsls/DSL:-AshAuthentication.Strategy.Oidc.cheatmd, lib/ash_authentication/strategies/oauth2/plug.ex
Applies to both OAuth2 and OpenID Connect.
With this the developer can provide either the full URL or the URL up to the AuthPlug path. If the suffix is already there we won't add it again.
Should make it easier to get it on the first try.
=> Change redirect_uri secret to be more flexible

lib/ash_authentication/plug/helpers.ex
I'm pretty sure `plug :match` and `plug :dispatch` are required when using `Plug.Router`
=> better Plug.Router example

documentation/dsls/DSL:-AshAuthentication.TokenResource.md, documentation/dsls/DSL:-AshAuthentication.UserIdentity.md, documentation/dsls/DSL:-AshAuthentication.md, lib/ash_authentication/dsl.ex, lib/ash_authentication/token_resource.ex, lib/ash_authentication/token_resource/transformer.ex, lib/ash_authentication/transformer.ex, lib/ash_authentication/user_identity.ex, lib/ash_authentication/user_identity/transformer.ex, lib/ash_authentication/utils.ex
Infer `api` set by `use Ash.Resource, api: ...` in `authentication`, `token` and `user_identity` sections.
Safe to remove `required: true` from `api` options because those sections verifiers already do verify that `api` is set and valid.
=> improvement: infer `api` from a resource

documentation/tutorials/getting-started-with-authentication.md
It's `resources/user.ex` earlier in the file so presumably it's supposed to be `resources/user.ex` here too.
=> fix incorrect file name in tutorial

documentation/tutorials/get-started.md
Fixes an issue in the 'Get Started' section where the code example was missing an import, which then made the code break.
=> docs: add snippet to help enable policy authorizers

documentation/tutorials/get-started.md
A few small changes to the tutorial to make the sections related to secrets a little less insecure. It's still not super secure, but I think it serves as a better jumping-off point which sends users in the right direction.
- Use a bang function to ensure that the `signing_secret` will raise an exception if it is absent from the config (instead of just silently evaluating to `nil`)
- Add config example for the secret signing token
- Add warning so that users are informed about the security implications of using the basic configuration provided by the tutorial
- Rearrange the sections a bit so the `Token Generation` section comes after the relevant code example
=> docs: improve security in the 'Get Started' guide

documentation/tutorials/get-started.md
Just a couple little changes to fix some issues related to using this tutorial with Ash 3.0.
- Use newer `ash_authentication` version since old version had dependency resolution errors
- Add `ash-functions` to the extensions list
- Fixes compiler warning when the item is missing
=> docs: change 'Get Started' guide for Ash 3.0 compatibility

documentation/tutorials/google.md
Small doc PR that reflects what worked for me when setting up google oauth.
The base_url is optional, so I removed it from the tutorial.
=> Update Google OAuth Tutorial

lib/ash_authentication/jwt.ex, lib/ash_authentication/verifier.ex, test/ash_authentication/user_with_bad_token_test.exs
During a refactor of the auth resources, the `tokens.token_resource` field was not updated properly on my user resource, and so I ended up getting a very vague `:error` result when trying to create tokens, without any other context. It was caused by the module not existing, but the current checks only check that the value configured is an atom.
Initial error when trying to log in:
```elixir
[error] | file=gen_server.erl line=2474 mfa=:gen_server.error_info/8 [22:44:23.824]: GenServer #PID<0.1271.0> terminating
** (MatchError) no match of right hand side value: :error
(ash_authentication 4.0.1) lib/ash_authentication/strategies/password/sign_in_preparation.ex:117: AshAuthentication.Strategy.Password.SignInPreparation.generate_token/3
(ash_authentication 4.0.1) …
```
=> Do a compile-time check to make sure that the configured `token_resource` is an Ash.Resource

lib/ash_authentication.ex, lib/ash_authentication/strategies/oauth2/plug.ex
Allow users to customize the behavior of the http client used by the oauth-based strategies by configuring a http adapter.
=> improvement: enable custom `http_adapters`

config/dev.exs, config/test.exs, lib/ash_authentication/dsl.ex, lib/ash_authentication/strategies/oauth2.ex, lib/ash_authentication/strategies/oauth2/dsl.ex, lib/ash_authentication/strategies/oauth2/plug.ex, lib/ash_authentication/strategies/oidc/dsl.ex, test/support/example/user.ex
Currently `trusted_audiences` is not usable since it is not passed to Assent as a config value.
This pull request makes `trusted_audiences` a secret so it is configurable at runtime and sets `trusted_audiences` in the assent config.
=> fix: actually use 'trusted_audiences' in oauth2 strategy

documentation/tutorials/github.md, documentation/tutorials/google.md
Ensure oauth users cannot login with unconfirmed account https://github.com/team-alembic/ash_authentication/issues/443
=> Update docs to account for unconfirmed users

lib/ash_authentication/strategies/password/actions.ex
The way options where passed tenant was ignored by the Ash.create as it was not translated as options.
=> fix: setup options properly for ash 3.0

lib/ash_authentication/strategies/apple/dsl.ex
Since the changes in #800 The OIDC strategy takes strings instead of atoms for the `client_authentication_method`.
The Apple dsl was still casting this option to an atom, which prevented compilation with an error.
Removed the casting from atom to string and everything compiles again :)
=> Fix Apple strategy

lib/ash_authentication/strategies/password/request_password_reset.ex
In the case where the request password reset action was called directly without the wrapping `Strategy.action/4` the inner `get_by...` action is denied by the default policy.
=> fix(RequestPasswordReset): fails when action called directly.

lib/ash_authentication/sender.ex
In the Magic Link strategy, the `send` function is called with either a user (if logging in to an existing account) or just an email address (if creating a new account). The typespec should reflect this!
=> fix: Use correct typespec for `AshAuthentication.Sender.send/3` callback

lib/ash_authentication/validations/attribute.ex
This PR addresses an issue where identities concatenated with primary_key does not preserve the correct nested structure. Specifically, when:
* primary_key is [:id]
* identities is [[:org, :staff_number], [:ssn], [:email]]
The resulting value becomes [[:org, :staff_number], [:ssn], [:email], :id], but it should be [[:org, :staff_number], [:ssn], [:email], [:id]].
This fix ensures that primary_key is correctly wrapped in a list when concatenated, resulting in the expected structure.
=> Fix identities concatenation to include primary_key in proper format

lib/ash_authentication/jwt.ex
In some cases, a tenant cannot be directly converted to a string.
=> Fix converting tenant to string

CHANGELOG.md, lib/ash_authentication/user_identity/upsert_identity_change.ex, test/ash_authentication/strategies/oauth2/actions_test.exs
Some providers like `Github` return an `uid` value as an _integer_, not `:string` which is the only type that was accepted. Now the value gets converted if it's not a string.
=> UID conversion to string added

lib/ash_authentication/strategies/password/actions.ex, lib/ash_authentication/strategies/password/sign_in_preparation.ex, test/ash_authentication/strategies/password/actions_test.exs
The actual `:sign_in_with_token` implementation is not taking into account if the account confirmation is required and automatically logs in the user.
=> fix: fixed `:sign_in_with_token` that was logging in user automatically even if confirmation is required and account is not confirmed

lib/ash_authentication/strategies/oauth2/plug.ex
`Assent.Config` removed in `0.3.0`; this required a change in the `:oauth2` strategy
=> Fixed the used of `Assent.Config`

documentation/tutorials/confirmation.md, mix.exs
Pinned `Assent version` (fixes https://github.com/team-alembic/ash_authentication/issues/883) and removed a wrong link from docs.
=> Fixed a link in the docs and pinned `Assent` to `0.2`

lib/ash_authentication/add_ons/confirmation/transformer.ex, lib/mix/tasks/ash_authentication.install.ex
The following commit was made to not enforce the type of the `expires_at` field so extended it to `confirm_at`
https://github.com/team-alembic/ash_authentication/commit/a305d462c412546ad3afab829aeaa9cb9d8ad75b#diff-fec59acf8cbd378e0230f6426f1ef645455e4539397bf7c9f659d6a66624f1c8
The reason being that I'm using `AshPostgres.TimestamptzUsec` instead
=> Do not enforce confirm_at attribute type

.tool-versions, lib/ash_authentication/secret.ex
Feel free to dismiss the `tool-versions` update, i just like to use the latest otp and elixir when possible.
=> make sure to point to right function for deprecation for AshAuthentication.Secret.secret_for/3

documentation/dsls/DSL-AshAuthentication.md, lib/ash_authentication/dsl.ex
This can be used by extensions which provide methods for users of other systems to authenticate using AA as the source of truth.
=> improvement: Add a patchable empty `authentication.providers` section.

lib/ash_authentication/igniter.ex
Since secret_for/3 is marked as deprecated, igniter should generate secret_for/4.
=> replace secret_for/3 with secret_for/4 in the igniter.ex

documentation/tutorials/auth0.md
If you start a project from scratch using the Ash bootstrapper you might end up in a situation where your `User` resource doesn't have an email attribute. This commit explains what to do in that case.
Nit: I've also added an arg to `secret_for` as the previous `/3` is deprecated.
=> Minor tweaks to Auth0 strategy

documentation/tutorials/confirmation.md
Hi @zachdaniel,
Thank you for helping me out. Based on previous [discord thread](https://discord.com/channels/711271361523351632/1253437793053577226/1361720542746640618), my intention here is to understand on how to use [`require_confirmed_with`](https://hexdocs.pm/ash_authentication/confirmation.html#blocking-unconfirmed-users-from-logging-in) when blocking unconfirmed users from logging in.
If you allow this PR, which code below is appropriate?
Option A:
```elixir
authentication do
...
add_ons do
confirmation :confirm_new_user do
...
end
end
strategies do
strategy :password do
...
require_confirmed_with :confirm_new_user
end
end
end
```
Option B:
```elixir
strategies do
strategy :password do
...
require_confirmed_with :confirmed_at
end
end
```
=> Update docs on using require_confirmed_with options

lib/ash_authentication/strategies/password/request_password_reset.ex
👋 After talking with Zach Daniel, I provide this PR. It will pass along the context given to the action running https://github.com/team-alembic/ash_authentication/blob/main/lib/ash_authentication/strategies/password/request_password_reset.ex 
```
strategy = Info.strategy!(User, :password)
strategy.resource
|> AshPhoenix.Form.for_action(strategy.resettable.request_password_reset_action_name,
context: %{otp_app: :foo}
)
```
You can now access `otp_app` under `opts` in the sender using `use AshAuthentication.Sender` resulting in something like:
```
defmodule SendNewUserConfirmationEmail do
use AshAuthentication.Sender
...
@impl true
def send(user, token, opts) do
<-- Here you can do something with opts[:otp_app] -->
end
...
end
```
=> improvement: pass along the action_input.context to the send_opts.

documentation/dsls/DSL-AshAuthentication.Strategy.Slack.md, lib/ash_authentication/add_ons/confirmation.ex, lib/ash_authentication/add_ons/log_out_everywhere.ex, lib/ash_authentication/strategies/api_key.ex, lib/ash_authentication/strategies/custom.ex, lib/ash_authentication/strategies/custom/transformer.ex, lib/ash_authentication/strategies/custom/verifier.ex, lib/ash_authentication/strategies/magic_link.ex, lib/ash_authentication/strategies/password.ex, lib/ash_authentication/strategies/slack.ex, lib/ash_authentication/validations.ex, test/support/example/only_marties_at_the_party.ex, test/support/example_multi_tenant/only_marties_at_the_party.ex
It's only needed when you recycle another strategy's DSL entity as your own. This is done a lot by all the OAuth2 and OIDC strategies which use the same OAuth2 struct behind the scenes.
Closes #992.
=> improvement(Strategy.Custom): The `strategy_module` field is no longer required.

documentation/topics/testing.md
Fixes an issue with the testing example code, which assigns a `new_conn` but then wrongly returns the old `conn`:
```elixir
new_conn =
conn
|> Phoenix.ConnTest.init_test_session(%{})
|> AshAuthentication.Plug.Helpers.store_in_session(user)
%{context | conn: conn}  # <-- Error is here, should be new_conn
```
=> Return the new_conn instead of the old conn

documentation/dsls/DSL-AshAuthentication.Strategy.Password.md, documentation/topics/testing.md, documentation/tutorials/confirmation.md, lib/ash_authentication/strategies/password/dsl.ex
Clarify that `require_confirmed_with` refers to a field name, not the confirmation add-on.
=> Improve docs for `require_confirmed_with` in password strategy

lib/ash_authentication/strategies/api_key/sign_in_preparation.ex, lib/ash_authentication/strategies/magic_link/sign_in_change.ex, lib/ash_authentication/strategies/oauth2/sign_in_preparation.ex
Use `Info.find_strategy` for looking up the strategy instead of `Info.strategy_for_action` directly.
The motivation for this change is that `ash_events` does some "clever" wrapping/renaming of actions when tracking events on resources.
When it is used on a resource that is also set up with `AshAuthentication`, the names of the various sign_in-actions get changed, and `Info.strategy_for_action` blows up since there is no strategy defined for the action after it has been renamed to something else than for example `sign_in_with_magic_link`.
The solution is to add a `change set_context(%{strategy_name}, <strategy>)` to the sign-in actions when using `ash_events`, but this will only work if the strategy is determined through `Info.find_strategy` 😅 
For context: …
=> Info.strategy_for_action/2 -> Info.find_strategy/3

lib/ash_authentication/strategies/magic_link/request.ex
This change helps to pass context to the mail sender.
This can be used to send a specific mail template to the user after an event happened to inform the user and provide a magic link to view information about the event in the application.
=> improvement: pass magic link request source context to mail sender

lib/ash_authentication/strategies/password/hash_password_change.ex
Updated `change` method in `AshAuthentication.Strategy.Password.HashPasswordChange` per issue #1057
=> feat: enhance error messages in hash_password_change.ex

lib/mix/tasks/ash_authentication.add_strategy.ex, test/mix/tasks/ash_authentication.add_strategy_test.exs
I was going to fat-finger a pr to get `ensure_get_by_action` uses `get_by` instead of `get?` & `filter`. But the tests fail because the output is actually `get_by(:email)` instead of the expected `get_by :email` . 
First, is it intentional that `ensure_get_by_action` is set up the way it is? Or is there something wrong with my local setup that is generating that out?
=> improve: ensure_get_by_action uses get_by
